name: Build the Android files from NextJS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Android SDK and Java from Ubuntu repos
      run: sudo apt update && sudo apt dist-upgrade -y && sudo apt install android-sdk openjdk-11-jdk -y
    - name: Execute the build.sh file
      run: build_android.sh
